server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: 你的邮箱授权码
    # 发送者邮箱地址
    username: 你的邮箱
    # 端口（不同邮箱端口号不同）
    port: 25

  # Redis配置
  redis:
    # 连接超时时间
    timeout: 10000ms
    # Redis服务器地址
    host: 127.0.0.1
    # Redis密码
    password: 123456
    # Redis服务器端口
    port: 6379
    # 选择哪个库，默认0库
    database: 2
    lettuce:
      pool:
        # 最大连接数，默认 8
        max-active: 1024
        # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-wait: 10000ms
        # 最大空闲连接，默认 8
        max-idle: 200
        # 最小空闲连接，默认 0
        min-idle: 5

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: guest
    # 密码
    password: guest
    # 服务器地址
    host: 192.168.196.131
    # 端口
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual